# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a3a33a57b25b50cf947f62725a6afe7c096c7e9728e56c4537d0d750852799f122fd0571a9fd7c3bd463e44a149d3094f11bf62a434f54f4fa36581d114bc42

test:
  secret_key_base: 36465ae2588354a921ad136bf4d04cdff4cf4aa5be2dc6edd9bc4e89ba92a601d0286244aac3570fd75358507784485b20d31ee874a5d3e07f84abfe53e1b048

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
